print("I am totally new to Python\n As I came to know it's new and has a good demand I started using it")
print("Thankfully I got some good videos in youtube")
print("Hopefully it will be useful in my carrier")
print("Thanks all for sharing some valuable time with me")
print("miss u all a lot")
